### ISSUE TITLE
Another (faster and builtin) alternative: max(array[key_1, ..., value]) = argmax(value, key_1, ...)

### ISSUE THREAD

**Issue by phiresky** [bashtanov/argm#4]
I'm writing this here since i just spent a long time searching for a solution for this problem without installing an extension, and also because it is faster than all the versions in the perf test (probably due to auto parallelization):

* distinct

   1M samples: Execution time: 887.764 ms
   10M samples: Execution time: 10849.624 ms

* sql_argmax

   1M samples: Execution time: 1464.047 ms
   10M samples: Execution time: 15333.772 ms

* argmax       (from this repo)                                             

   1M samples: Execution time: 186.949 ms
   10M samples: Execution time: 2162.360 ms
                                                                 
* max(array)

   1M samples: Execution time: **127.789 ms**
   10M samples: Execution time: **1370.459 ms**

I'm using `max(array[key_1, ..., value])` which works because ["Array comparisons compare the array contents element-by-element"](https://www.postgresql.org/docs/10/static/functions-array.html)

Specifically, for the benchmark the query looks like this:

```sql
explain analyze select grp, (max(array[d::text, t]))[2] from tbl group by grp order by grp;
```

The only restriction is that `value` must be of the same type as the keys, which for me is not an issue since i'm comparing ints and my primary key is `bigint`. (In the example I cast the date to string which is still correct due to ISO8601 though probably slower).

**Comment by phiresky** [comment]
Query plan (10M rows):
```
                                                                    QUERY PLAN                                                                    
--------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize GroupAggregate  (cost=166669.14..166669.22 rows=3 width=36) (actual time=1362.089..1362.091 rows=3 loops=1)
   Group Key: grp
   ->  Sort  (cost=166669.14..166669.16 rows=6 width=36) (actual time=1362.084..1362.084 rows=9 loops=1)
         Sort Key: grp
         Sort Method: quicksort  Memory: 26kB
         ->  Gather  (cost=166669.04..166669.07 rows=6 width=36) (actual time=1362.074..1362.077 rows=9 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               ->  Partial HashAggregate  (cost=166669.04..166669.07 rows=3 width=36) (actual time=1360.854..1360.855 rows=3 loops=3)
                     Group Key: grp
                     ->  Parallel Seq Scan on tbl  (cost=0.00..125002.52 rows=4166652 width=37) (actual time=0.014..299.656 rows=3333333 loops=3)
 Planning time: 0.043 ms
 Execution time: 1363.145 ms
```

**Comment by bashtanov** [comment]
Thanks @phiresky, this is a known method, you [even can try it with different data types](https://www.slideshare.net/AlexeyBashtanov/postgresql-performance-for-queries-with-grouping#53). Worst case you can either use a named composite type or do the array-of-records trick with unpacking using lateral+unnest:
```
select group_key,
       payload
from (
    select sort_key % 10 group_key,
           max(array[(sort_key, payload)]) packed
    from (
        select k sort_key,
               random() || '-' || k::text payload
        from generate_series(1, 100) k
    ) _
    group by group_key
) j cross join lateral unnest(packed) z (sort_key int, payload text);
```

[My measurings](https://www.slideshare.net/AlexeyBashtanov/postgresql-performance-for-queries-with-grouping#56) involved "square" distribution: the number of groups was the same as the number of elements per group. In your examples, what was 1M/10M? Did you have a single group only? When I did my benchmarks 9.6 was not yet out, so `max` could not benefit from parallelization.

Parallelization is coming soon BTW, see #2.
For now, parallelized queries and tricks with `max` may be a better option, provided you optimize for speed not for CPU usage, and you manage to do the type tweaking.

**Comment by phiresky** [comment]
Thanks for the link.

Might be good to mention the alternatives here in this repo, since this is the second result when googling `argmax postgresql` (and the first result purely contains crap that is impossible to index)

>  In your examples, what was 1M/10M? 

I just used your code almost unchanged:

```diff
diff --git a/sql/perf-argmax.sql b/sql/perf-argmax.sql
index 9c53115..3fe75c7 100644
--- a/sql/perf-argmax.sql
+++ b/sql/perf-argmax.sql
@@ -12,7 +12,7 @@ select d,
 	random() || ' ' || d::text t,
 	floor(random() * 3)::int grp
 from (
-	select current_date - generate_series(1, 1000000/*0*/) d
+	select current_date + generate_series(1, 10000000) d
 	order by random()
 ) _;
 analyze tbl;
@@ -24,5 +24,6 @@ explain analyze select * from tbl;
 explain analyze select distinct on (grp) grp, t from tbl order by grp, d desc;
 explain analyze select grp, sql_argmax(t, d) from tbl group by grp order by grp;
 explain analyze select grp, argmax(t, d) from tbl group by grp order by grp;
+explain analyze select grp, (max(array[d::text, t]))[2] from tbl group by grp order by grp;
 
 rollback;
```

**Comment by bashtanov** [comment]
@phiresky I've added parallelism, so it's max-array no longer faster. However I've added this method to the performance tests.

**Comment by phiresky** [comment]
Nice. Thanks!
